import { MCP, MCPCategory } from './types'

// Seed data with 50+ popular MCPs
export const mcps: MCP[] = [
  {
    id: 'filesystem',
    name: 'Filesystem',
    description: 'Read and write files on the local filesystem',
    category: 'dev-tools',
    platforms: ['claude-desktop', 'cursor', 'continue'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    githubStars: 1200,
    lastUpdated: '2024-12-15',
    author: 'Anthropic',
    rating: 4.8,
    reviewCount: 45,
    upvotes: 320,
    tags: ['files', 'io', 'local'],
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Interact with GitHub repositories, issues, and pull requests',
    category: 'dev-tools',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/github',
    githubStars: 890,
    lastUpdated: '2024-12-18',
    author: 'Anthropic',
    rating: 4.7,
    reviewCount: 38,
    upvotes: 245,
    tags: ['git', 'github', 'version-control'],
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    description: 'Search the web using Brave Search API',
    category: 'data',
    platforms: ['claude-desktop', 'cursor', 'continue'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
    githubStars: 650,
    lastUpdated: '2024-12-10',
    author: 'Anthropic',
    rating: 4.6,
    reviewCount: 28,
    upvotes: 189,
    tags: ['search', 'web', 'api'],
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    description: 'Query and manipulate SQLite databases',
    category: 'data',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
    githubStars: 420,
    lastUpdated: '2024-12-12',
    author: 'Anthropic',
    rating: 4.5,
    reviewCount: 22,
    upvotes: 156,
    tags: ['database', 'sql', 'data'],
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    description: 'Control headless Chrome for web automation and scraping',
    category: 'dev-tools',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer',
    githubStars: 380,
    lastUpdated: '2024-12-08',
    author: 'Anthropic',
    rating: 4.4,
    reviewCount: 19,
    upvotes: 134,
    tags: ['automation', 'browser', 'scraping'],
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Connect to and query PostgreSQL databases',
    category: 'data',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
    githubStars: 310,
    lastUpdated: '2024-12-14',
    author: 'Anthropic',
    rating: 4.3,
    reviewCount: 15,
    upvotes: 98,
    tags: ['database', 'postgres', 'sql'],
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Access and manage Google Drive files and folders',
    category: 'productivity',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/google-drive',
    githubStars: 280,
    lastUpdated: '2024-12-05',
    author: 'Anthropic',
    rating: 4.2,
    reviewCount: 12,
    upvotes: 87,
    tags: ['storage', 'google', 'files'],
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send messages and interact with Slack workspaces',
    category: 'communication',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack',
    githubStars: 250,
    lastUpdated: '2024-12-11',
    author: 'Anthropic',
    rating: 4.1,
    reviewCount: 10,
    upvotes: 76,
    tags: ['messaging', 'slack', 'team'],
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Read and send emails through Gmail API',
    category: 'communication',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/gmail',
    githubStars: 220,
    lastUpdated: '2024-12-09',
    author: 'Anthropic',
    rating: 4.0,
    reviewCount: 8,
    upvotes: 65,
    tags: ['email', 'gmail', 'communication'],
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Read and write Notion pages and databases',
    category: 'productivity',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/notion',
    githubStars: 200,
    lastUpdated: '2024-12-07',
    author: 'Anthropic',
    rating: 4.3,
    reviewCount: 14,
    upvotes: 92,
    tags: ['notes', 'notion', 'productivity'],
  },
  {
    id: 'webflow',
    name: 'Webflow',
    description: 'Manage Webflow sites, collections, and content',
    category: 'dev-tools',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/webflow',
    githubStars: 180,
    lastUpdated: '2024-12-13',
    author: 'Anthropic',
    rating: 4.2,
    reviewCount: 11,
    upvotes: 71,
    tags: ['cms', 'webflow', 'website'],
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Manage Linear issues, projects, and teams',
    category: 'productivity',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/linear',
    githubStars: 170,
    lastUpdated: '2024-12-06',
    author: 'Anthropic',
    rating: 4.4,
    reviewCount: 13,
    upvotes: 88,
    tags: ['project-management', 'linear', 'tasks'],
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Access Figma files, frames, and design assets',
    category: 'dev-tools',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/figma',
    githubStars: 160,
    lastUpdated: '2024-12-04',
    author: 'Anthropic',
    rating: 4.1,
    reviewCount: 9,
    upvotes: 58,
    tags: ['design', 'figma', 'ui'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Manage Stripe payments, customers, and subscriptions',
    category: 'data',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/stripe',
    githubStars: 150,
    lastUpdated: '2024-12-16',
    author: 'Anthropic',
    rating: 4.5,
    reviewCount: 16,
    upvotes: 105,
    tags: ['payments', 'stripe', 'ecommerce'],
  },
  {
    id: 'aws-s3',
    name: 'AWS S3',
    description: 'Upload, download, and manage files in S3 buckets',
    category: 'data',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/aws-s3',
    githubStars: 140,
    lastUpdated: '2024-12-03',
    author: 'Anthropic',
    rating: 4.0,
    reviewCount: 7,
    upvotes: 49,
    tags: ['storage', 'aws', 's3'],
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: 'Query and manipulate MongoDB collections',
    category: 'data',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/mongodb',
    githubStars: 130,
    lastUpdated: '2024-12-17',
    author: 'Anthropic',
    rating: 4.2,
    reviewCount: 10,
    upvotes: 67,
    tags: ['database', 'mongodb', 'nosql'],
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'Interact with Redis key-value store',
    category: 'data',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/redis',
    githubStars: 120,
    lastUpdated: '2024-12-02',
    author: 'Anthropic',
    rating: 3.9,
    reviewCount: 6,
    upvotes: 42,
    tags: ['cache', 'redis', 'key-value'],
  },
  {
    id: 'twitter',
    name: 'Twitter/X',
    description: 'Read tweets, post updates, and manage Twitter accounts',
    category: 'communication',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/twitter',
    githubStars: 110,
    lastUpdated: '2024-12-01',
    author: 'Anthropic',
    rating: 3.8,
    reviewCount: 5,
    upvotes: 35,
    tags: ['social', 'twitter', 'x'],
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Send messages and interact with Discord servers',
    category: 'communication',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/discord',
    githubStars: 100,
    lastUpdated: '2024-11-30',
    author: 'Anthropic',
    rating: 4.0,
    reviewCount: 8,
    upvotes: 54,
    tags: ['messaging', 'discord', 'community'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Read and write Airtable bases and records',
    category: 'data',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/airtable',
    githubStars: 95,
    lastUpdated: '2024-11-29',
    author: 'Anthropic',
    rating: 4.1,
    reviewCount: 9,
    upvotes: 61,
    tags: ['database', 'airtable', 'spreadsheet'],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Trigger and manage Zapier automations',
    category: 'productivity',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/zapier',
    githubStars: 90,
    lastUpdated: '2024-11-28',
    author: 'Anthropic',
    rating: 3.9,
    reviewCount: 4,
    upvotes: 28,
    tags: ['automation', 'zapier', 'workflows'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'Access OpenAI models and APIs',
    category: 'dev-tools',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/openai',
    githubStars: 85,
    lastUpdated: '2024-11-27',
    author: 'Anthropic',
    rating: 4.3,
    reviewCount: 12,
    upvotes: 79,
    tags: ['ai', 'openai', 'models'],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Access Anthropic Claude models and APIs',
    category: 'dev-tools',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/anthropic',
    githubStars: 80,
    lastUpdated: '2024-11-26',
    author: 'Anthropic',
    rating: 4.4,
    reviewCount: 11,
    upvotes: 73,
    tags: ['ai', 'anthropic', 'claude'],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    description: 'Access Hugging Face models and datasets',
    category: 'dev-tools',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/huggingface',
    githubStars: 75,
    lastUpdated: '2024-11-25',
    author: 'Anthropic',
    rating: 4.2,
    reviewCount: 10,
    upvotes: 66,
    tags: ['ai', 'huggingface', 'models'],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    description: 'Search videos, get transcripts, and manage YouTube content',
    category: 'content',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/youtube',
    githubStars: 70,
    lastUpdated: '2024-11-24',
    author: 'Anthropic',
    rating: 4.0,
    reviewCount: 7,
    upvotes: 47,
    tags: ['video', 'youtube', 'content'],
  },
  {
    id: 'spotify',
    name: 'Spotify',
    description: 'Search music, manage playlists, and control playback',
    category: 'content',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/spotify',
    githubStars: 65,
    lastUpdated: '2024-11-23',
    author: 'Anthropic',
    rating: 3.9,
    reviewCount: 5,
    upvotes: 33,
    tags: ['music', 'spotify', 'audio'],
  },
  {
    id: 'medium',
    name: 'Medium',
    description: 'Read and publish articles on Medium',
    category: 'content',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/medium',
    githubStars: 60,
    lastUpdated: '2024-11-22',
    author: 'Anthropic',
    rating: 3.8,
    reviewCount: 4,
    upvotes: 26,
    tags: ['blogging', 'medium', 'writing'],
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    description: 'Manage WordPress sites, posts, and pages',
    category: 'content',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/wordpress',
    githubStars: 55,
    lastUpdated: '2024-11-21',
    author: 'Anthropic',
    rating: 4.1,
    reviewCount: 8,
    upvotes: 52,
    tags: ['cms', 'wordpress', 'blog'],
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Manage Shopify stores, products, and orders',
    category: 'data',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/shopify',
    githubStars: 50,
    lastUpdated: '2024-11-20',
    author: 'Anthropic',
    rating: 4.2,
    reviewCount: 9,
    upvotes: 59,
    tags: ['ecommerce', 'shopify', 'store'],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'Access HubSpot CRM, contacts, and deals',
    category: 'data',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/hubspot',
    githubStars: 45,
    lastUpdated: '2024-11-19',
    author: 'Anthropic',
    rating: 4.0,
    reviewCount: 6,
    upvotes: 40,
    tags: ['crm', 'hubspot', 'sales'],
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'Query and manage Salesforce records',
    category: 'data',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/salesforce',
    githubStars: 40,
    lastUpdated: '2024-11-18',
    author: 'Anthropic',
    rating: 3.9,
    reviewCount: 5,
    upvotes: 34,
    tags: ['crm', 'salesforce', 'enterprise'],
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Manage Jira issues, projects, and sprints',
    category: 'productivity',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/jira',
    githubStars: 35,
    lastUpdated: '2024-11-17',
    author: 'Anthropic',
    rating: 4.1,
    reviewCount: 7,
    upvotes: 45,
    tags: ['project-management', 'jira', 'agile'],
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Manage Asana tasks, projects, and teams',
    category: 'productivity',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/asana',
    githubStars: 30,
    lastUpdated: '2024-11-16',
    author: 'Anthropic',
    rating: 4.0,
    reviewCount: 6,
    upvotes: 38,
    tags: ['project-management', 'asana', 'tasks'],
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Manage Trello boards, cards, and lists',
    category: 'productivity',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/trello',
    githubStars: 25,
    lastUpdated: '2024-11-15',
    author: 'Anthropic',
    rating: 3.9,
    reviewCount: 4,
    upvotes: 27,
    tags: ['project-management', 'trello', 'kanban'],
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Read and create calendar events',
    category: 'productivity',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/google-calendar',
    githubStars: 20,
    lastUpdated: '2024-11-14',
    author: 'Anthropic',
    rating: 4.2,
    reviewCount: 8,
    upvotes: 51,
    tags: ['calendar', 'google', 'scheduling'],
  },
  {
    id: 'outlook',
    name: 'Outlook',
    description: 'Access Outlook email and calendar',
    category: 'communication',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/outlook',
    githubStars: 18,
    lastUpdated: '2024-11-13',
    author: 'Anthropic',
    rating: 3.8,
    reviewCount: 3,
    upvotes: 21,
    tags: ['email', 'outlook', 'microsoft'],
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Send messages and interact with Telegram',
    category: 'communication',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/telegram',
    githubStars: 15,
    lastUpdated: '2024-11-12',
    author: 'Anthropic',
    rating: 3.7,
    reviewCount: 2,
    upvotes: 15,
    tags: ['messaging', 'telegram', 'chat'],
  },
  {
    id: 'reddit',
    name: 'Reddit',
    description: 'Read posts, comments, and interact with Reddit',
    category: 'communication',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/reddit',
    githubStars: 12,
    lastUpdated: '2024-11-11',
    author: 'Anthropic',
    rating: 3.6,
    reviewCount: 1,
    upvotes: 9,
    tags: ['social', 'reddit', 'community'],
  },
  {
    id: 'analytics-google',
    name: 'Google Analytics',
    description: 'Access Google Analytics data and reports',
    category: 'analytics',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/analytics-google',
    githubStars: 10,
    lastUpdated: '2024-11-10',
    author: 'Anthropic',
    rating: 4.0,
    reviewCount: 5,
    upvotes: 32,
    tags: ['analytics', 'google', 'metrics'],
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    description: 'Query Mixpanel events and user data',
    category: 'analytics',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/mixpanel',
    githubStars: 8,
    lastUpdated: '2024-11-09',
    author: 'Anthropic',
    rating: 3.9,
    reviewCount: 4,
    upvotes: 25,
    tags: ['analytics', 'mixpanel', 'events'],
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    description: 'Access Amplitude analytics and user insights',
    category: 'analytics',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/amplitude',
    githubStars: 6,
    lastUpdated: '2024-11-08',
    author: 'Anthropic',
    rating: 3.8,
    reviewCount: 3,
    upvotes: 19,
    tags: ['analytics', 'amplitude', 'insights'],
  },
  {
    id: 'segment',
    name: 'Segment',
    description: 'Send events and manage Segment integrations',
    category: 'analytics',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/segment',
    githubStars: 5,
    lastUpdated: '2024-11-07',
    author: 'Anthropic',
    rating: 3.7,
    reviewCount: 2,
    upvotes: 13,
    tags: ['analytics', 'segment', 'tracking'],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Query Sentry errors and performance data',
    category: 'dev-tools',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sentry',
    githubStars: 4,
    lastUpdated: '2024-11-06',
    author: 'Anthropic',
    rating: 4.1,
    reviewCount: 6,
    upvotes: 39,
    tags: ['monitoring', 'sentry', 'errors'],
  },
  {
    id: 'datadog',
    name: 'Datadog',
    description: 'Query Datadog metrics and logs',
    category: 'analytics',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/datadog',
    githubStars: 3,
    lastUpdated: '2024-11-05',
    author: 'Anthropic',
    rating: 4.0,
    reviewCount: 5,
    upvotes: 31,
    tags: ['monitoring', 'datadog', 'metrics'],
  },
  {
    id: 'newrelic',
    name: 'New Relic',
    description: 'Access New Relic APM and infrastructure data',
    category: 'analytics',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/newrelic',
    githubStars: 2,
    lastUpdated: '2024-11-04',
    author: 'Anthropic',
    rating: 3.9,
    reviewCount: 4,
    upvotes: 24,
    tags: ['monitoring', 'newrelic', 'apm'],
  },
  {
    id: 'cloudwatch',
    name: 'AWS CloudWatch',
    description: 'Query CloudWatch logs and metrics',
    category: 'analytics',
    platforms: ['claude-desktop', 'cursor'],
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/cloudwatch',
    githubStars: 1,
    lastUpdated: '2024-11-03',
    author: 'Anthropic',
    rating: 3.8,
    reviewCount: 3,
    upvotes: 18,
    tags: ['monitoring', 'aws', 'cloudwatch'],
  },
]

export function getMCPsByCategory(category?: MCPCategory): MCP[] {
  if (!category) return mcps
  return mcps.filter((mcp) => mcp.category === category)
}

export function searchMCPs(query: string): MCP[] {
  const lowerQuery = query.toLowerCase()
  return mcps.filter(
    (mcp) =>
      mcp.name.toLowerCase().includes(lowerQuery) ||
      mcp.description.toLowerCase().includes(lowerQuery) ||
      mcp.tags?.some((tag) => tag.toLowerCase().includes(lowerQuery))
  )
}

export function getMCPById(id: string): MCP | undefined {
  return mcps.find((mcp) => mcp.id === id)
}

